# Generated by Django 4.2.7 on 2023-12-03 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashFlow', '0003_ethereumdailymeta_ethereumdaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumdaily',
            name='meta_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashFlow.ethereumdailymeta'),
        ),
    ]
